@endpoint = users
@localhost = http://localhost:3001
@deployed =
@base_url = {{localhost}}
@url = {{base_url}}/api/{{endpoint}}

#####
# Valid

POST {{url}}
Content-Type: application/json

{
  "username": "johndoe",
  "name": "John Doe",
  "password": "password"
}

###

DELETE {{url}}/6398e1b67c073bc6c44fff86